# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/tmp/CSExperiment_MIPS/Project_Singal_CPU/Project_Singal_CPU.srcs/sources_1/ip/Instr_Mem/Instr_Mem.xci
# IP: The module: 'Instr_Mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/tmp/CSExperiment_MIPS/Project_Singal_CPU/Project_Singal_CPU.srcs/sources_1/ip/Instr_Mem/Instr_Mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Instr_Mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/tmp/CSExperiment_MIPS/Project_Singal_CPU/Project_Singal_CPU.srcs/sources_1/ip/Instr_Mem/Instr_Mem.xci
# IP: The module: 'Instr_Mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/tmp/CSExperiment_MIPS/Project_Singal_CPU/Project_Singal_CPU.srcs/sources_1/ip/Instr_Mem/Instr_Mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Instr_Mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
